"""
src/api/main.py
---------------
FastAPI REST API for DocSage.

Endpoints:
  GET  /health  — liveness check (no auth, no DB access)
  POST /query   — full RAG pipeline: retrieve + generate

Interactive API docs are auto-generated by FastAPI at:
  http://localhost:8000/docs  (Swagger UI)
  http://localhost:8000/redoc (ReDoc)

Run with:
  uvicorn src.api.main:app --reload --port 8000
"""

import logging
import time
from typing import List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from src.retrieval.search import search_documents
from src.generation.generate import generate_answer

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

app = FastAPI(
    title="DocSage API",
    description="Multimodal RAG agent for AWS technical documentation",
    version="1.0.0",
)

# Allow Streamlit frontend (running on a different port) to call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict to specific origins in production
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class QueryRequest(BaseModel):
    question: str = Field(
        ...,
        description="Natural language question about AWS documentation",
        example="What are the six pillars of the Well-Architected Framework?",
    )
    top_k: Optional[int] = Field(
        default=5,
        description="Number of context chunks to retrieve (1-20)",
        ge=1,
        le=20,
    )


class SourceRef(BaseModel):
    source_doc: str
    page_num: int


class QueryResponse(BaseModel):
    answer: str
    refused: bool
    sources: List[SourceRef]
    latency_ms: float


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health")
def health():
    """Liveness check. Returns 200 if the API is running."""
    return {"status": "ok", "service": "DocSage API"}


@app.post("/query", response_model=QueryResponse)
def query(request: QueryRequest):
    """
    Run the full DocSage RAG pipeline for a question.

    1. Retrieves the most relevant documentation chunks (hybrid search + rerank)
    2. Generates a grounded, cited answer using the Groq LLM

    If the retrieved context doesn't support a confident answer, `refused` will
    be True and `answer` will be the refusal phrase.
    """
    start = time.perf_counter()

    try:
        chunks = search_documents(request.question, top_k=request.top_k)
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=503,
            detail=f"Index not built yet. Run scripts/build_index.py first. ({e})",
        )
    except Exception as e:
        logger.exception("Error during retrieval")
        raise HTTPException(status_code=500, detail=f"Retrieval error: {e}")

    try:
        result = generate_answer(request.question, chunks)
    except Exception as e:
        logger.exception("Error during generation")
        raise HTTPException(status_code=500, detail=f"Generation error: {e}")

    elapsed_ms = (time.perf_counter() - start) * 1000

    return QueryResponse(
        answer=result["answer"],
        refused=result["refused"],
        sources=[SourceRef(**s) for s in result["sources"]],
        latency_ms=round(elapsed_ms, 1),
    )
